# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 23:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOfOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('sur_name', models.CharField(blank=True, max_length=256, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('no_phone', models.TextField(blank=True, verbose_name='Контактный телефон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время внесения в базу')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения в базе')),
            ],
            options={
                'verbose_name_plural': 'Контактные администраторы',
                'verbose_name': 'Контактный администратор',
            },
        ),
        migrations.CreateModel(
            name='AuthorizedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('sur_name', models.CharField(blank=True, max_length=256, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('no_phone', models.TextField(blank=True, verbose_name='Контактный телефон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время внесения в базу')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения в базе')),
            ],
            options={
                'verbose_name_plural': 'Подписывающее договора лица',
                'verbose_name': 'Подписывающее договор лицо',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=80, verbose_name='Тип муниципального образования')),
                ('name', models.CharField(max_length=80, verbose_name='Наименование муниципального образования')),
                ('okato', models.CharField(max_length=32, verbose_name='Общероссийский классификатор объектов \n        административно-территориального деления')),
                ('oktmo', models.CharField(max_length=32, verbose_name='Общероссийский классификатор территорий муниципальных образований')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name_plural': 'Муниципальные образования',
                'verbose_name': 'Муниципальное образование',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_us', models.BooleanField(default=False, verbose_name='Загегистрирована ли организация')),
                ('full_name', models.CharField(max_length=512, verbose_name='Полное наименование')),
                ('name', models.CharField(max_length=80, verbose_name='Сокращённое наименование')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=12, verbose_name='КПП')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(verbose_name='Фактический адрес')),
                ('no_phone', models.TextField(verbose_name='Телефон бухгалтерии')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('no_users', models.PositiveSmallIntegerField(default=1, verbose_name='Заявляемое количество пользователей')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время внесения в базу')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения в базе')),
                ('district', models.ForeignKey(default=6, help_text='Муниципальное образование', on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='client.District')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='auth.Group')),
            ],
            options={
                'verbose_name_plural': 'Организации',
                'verbose_name': 'Организация',
                'permissions': (('can_view', 'Могут видеть доступные организации'), ('can_change', 'Могут менять данные об организации')),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/users', verbose_name='Изображение')),
                ('ip', models.GenericIPAddressField(verbose_name='IP пользователя')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='client.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Профили Пользователей',
                'verbose_name': 'Профиль Пользователя',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Наименование республики/края/области/округа')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name_plural': 'Республики / Края / Области / Округа',
                'verbose_name': 'Республика / Край / Область / Округ',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='client.Region'),
        ),
        migrations.AddField(
            model_name='authorizedperson',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_person', to='client.Organization'),
        ),
        migrations.AddField(
            model_name='adminoforganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='client.Organization'),
        ),
    ]
