# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-23 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burial_form', '0003_auto_20170923_0322'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Burial',
        ),
        migrations.RemoveField(
            model_name='deadmen',
            name='declarant',
        ),
        migrations.RemoveField(
            model_name='iddocument',
            name='person',
        ),
        migrations.RemoveField(
            model_name='place',
            name='cemetery',
        ),
        migrations.RemoveField(
            model_name='place',
            name='dead_man',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.DeleteModel(
            name='DeadMen',
        ),
        migrations.DeleteModel(
            name='Declarant',
        ),
        migrations.DeleteModel(
            name='IdDocument',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
