# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 23:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование документа')),
            ],
            options={
                'verbose_name_plural': 'Дополнительные документы',
                'verbose_name': 'Дополнительный документ',
            },
        ),
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcseries', models.CharField(blank=True, max_length=8, verbose_name='Серия')),
                ('dcnumber', models.CharField(blank=True, max_length=16, verbose_name='Номер')),
                ('dcaddress', models.CharField(blank=True, max_length=512, verbose_name='Адрес регистрации по месту жительства')),
                ('issued_by', models.CharField(blank=True, max_length=512, verbose_name='Кем выдан')),
                ('dcperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='catalog.DeadMen')),
            ],
            options={
                'verbose_name_plural': 'Св-ва о смерти',
                'verbose_name': 'Св-во о смерти',
            },
        ),
        migrations.CreateModel(
            name='Declarant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('sur_name', models.CharField(blank=True, max_length=256, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('no_phone', models.TextField(blank=True, verbose_name='Контактный телефон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время внесения в базу')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения в базе')),
            ],
            options={
                'verbose_name_plural': 'Заявители',
                'verbose_name': 'Заявитель',
            },
        ),
        migrations.CreateModel(
            name='FormNo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время внесения в базу')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения в базе')),
                ('responsible_for_burial_is_declarant', models.BooleanField(default=True, verbose_name='Является ли заявителем')),
                ('responsible_for_burial', models.CharField(blank=True, max_length=512, verbose_name='ФИО ответственного за захоронение')),
                ('burial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Burial')),
                ('cemetery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Cemetery')),
                ('dead_men', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.DeadMen')),
                ('declarant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='burial_form.Declarant')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Place')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Формы №1',
                'verbose_name': 'Форма №1',
            },
        ),
        migrations.AddField(
            model_name='additionaldocument',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burial_form.FormNo1'),
        ),
    ]
