# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-23 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burial_form', '0003_auto_20170923_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formno1',
            name='cemetery',
        ),
        migrations.RemoveField(
            model_name='formno1',
            name='dead_men',
        ),
        migrations.RemoveField(
            model_name='formno1',
            name='death_certificate',
        ),
        migrations.RemoveField(
            model_name='formno1',
            name='declarant',
        ),
        migrations.AlterField(
            model_name='formno1',
            name='responsible_for_burial_is_declarant',
            field=models.BooleanField(default=True, verbose_name='Является заявителем'),
        ),
    ]
