# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-23 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burial_form', '0004_auto_20170923_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burial',
            name='option',
            field=models.CharField(choices=[('P', 'настоящее'), ('F', 'будующее')], default='P', max_length=1, verbose_name='Тип захоронения'),
        ),
        migrations.AlterField(
            model_name='formno1',
            name='burial',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='formNo1', to='burial_form.Burial'),
        ),
        migrations.AlterField(
            model_name='formno1',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formNo1', to='burial_form.Place'),
        ),
    ]
